/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter } from "ethers";
import { Provider } from "ethers/providers";
import { BigNumber } from "ethers/utils";

export class OAXToken extends Contract {
  functions: {
    balanceOf(_owner: string): Promise<BigNumber>;

    allowance(_owner: string, _spender: string): Promise<BigNumber>;

    approve(
      _spender: string,
      _value: number | string
    ): Promise<ContractTransaction>;

    transferFrom(
      _from: string,
      _to: string,
      _value: number | string
    ): Promise<ContractTransaction>;

    decreaseApproval(
      _spender: string,
      _subtractedValue: number | string
    ): Promise<ContractTransaction>;

    transfer(
      _to: string,
      _value: number | string
    ): Promise<ContractTransaction>;

    increaseApproval(
      _spender: string,
      _addedValue: number | string
    ): Promise<ContractTransaction>;

    name(): Promise<string>;
    totalSupply(): Promise<BigNumber>;
    decimals(): Promise<BigNumber>;
    symbol(): Promise<string>;
  };
  filters: {
    Approval(
      owner: string | null,
      spender: string | null,
      value: null
    ): EventFilter;

    Transfer(from: string | null, to: string | null, value: null): EventFilter;
  };
}
