/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter } from "ethers";
import { Provider } from "ethers/providers";
import { BigNumber } from "ethers/utils";

export class ERC20 extends Contract {
  functions: {
    balanceOf(_who: string): Promise<BigNumber>;

    allowance(_owner: string, _spender: string): Promise<BigNumber>;

    approve(
      _spender: string,
      _value: number | string
    ): Promise<ContractTransaction>;

    transferFrom(
      _from: string,
      _to: string,
      _value: number | string
    ): Promise<ContractTransaction>;

    transfer(
      _to: string,
      _value: number | string
    ): Promise<ContractTransaction>;

    totalSupply(): Promise<BigNumber>;
  };
  filters: {
    Approval(
      owner: string | null,
      spender: string | null,
      value: null
    ): EventFilter;

    Transfer(from: string | null, to: string | null, value: null): EventFilter;
  };
}
