/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter } from "ethers";
import { Provider } from "ethers/providers";
import { BigNumber } from "ethers/utils";

export class Struct extends Contract {
  functions: {
    acceptStruct(s: {
      a: number | string;
      b: number | string;
    }): Promise<BigNumber>;

    returnStruct(a: number | string, b: number | string): Promise<object[]>;
  };
  filters: {};
}
